#!/usr/bin/env python
import os
import sys

if 'OPENSHIFT_REPO_DIR' in os.environ:
    ON_OPENSHIFT = True
else:
    ON_OPENSHIFT = False

if ON_OPENSHIFT:
    os.environ['DJANGO_SETTINGS_MODULE'] = 'tokoku.settings'
    sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'tokoku'))

    virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/venv/'
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python3.3/site-packages')

    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

    try:
        exec(compile(open(virtualenv).read(), virtualenv, 'exec'),	
            dict(__file__ = virtualenv) )
    except IOError:
        pass
else:				
    os.environ['DJANGO_SETTINGS_MODULE'] = 'tokoku.settings'
    sys.path.append('/home/endik/Documents/WorkSpace/Python/endikApp/VENV/OPENSHIFT/toko/wsgi/tokoku')

#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

#for ver 1.6.x
#import django.core.handlers.wsgi
#application = django.core.handlers.wsgi.WSGIHandler()

#for ver 1.7.x
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()






